chi3d:
  fps_train: 25
  fps_eval: 25
  augment_rotation: false
  augment_symmetry: false
  root: data/preprocessed/chi3d_smplx
  train_split_file: data/preprocessed/chi3d_smplx/chi3d_train.json
  val_split_file: data/preprocessed/chi3d_smplx/chi3d_val.json
  test_split_file: data/preprocessed/chi3d_smplx/chi3d_test.json
model_denoising:
  name: transformer_unidiffuser_3
  dim_timestep_embed: 128
  params:
    dim_hidden: 312
    num_layers: 8
    dim_feedforward: 2048
    nhead: 8
model:
  data_sbj_channels: 325
  data_second_sbj_channels: 325
  denoise_mode: sample
  beta_start: 1.0e-05
  beta_end: 0.008
  beta_schedule: linear
model_conditioning:
  use_gender_conditioning: true
  num_genders: 2
run:
  datasets:
  - chi3d
dataloader:
  batch_size: 1024
  workers: 12
  sampler: weighted
train:
  mixed_precision: 'no'
  limit_train_batches: null
  log_step_freq: 100
  checkpoint_freq: 5000
  max_steps: 50000
  early_stop: true
  early_stop_metric: "VAL_loss/total"
  early_stop_mode: "min"
  early_stop_patience: 8
  early_stop_min_delta: 0.0
  early_stop_warmup_epochs: 1
  early_stop_save_best: true
  limit_val_batches: null
  losses:
    denoise_1: 10.0
    denoise_2: 10.0
    smpl_v2v: 30.0
    second_smpl_v2v: 30.0
optimizer:
  type: torch
  name: AdamW
  lr: 0.00015
  weight_decay: 1.0e-06
  scale_learning_rate_with_batch_size: false
  gradient_accumulation_steps: 1
  clip_grad_norm: 5.0
  kwargs:
    betas:
    - 0.95
    - 0.999
scheduler:
  type: transformers
  name: cosine
  kwargs:
    num_warmup_steps: 8000
    num_training_steps: 50000
sample:
  # Fair NNBaseline-style sampling space: keep pose(+shape), force global=I6 and transl=0
  pose_only_like_baseline: false
eval:
  # Fair NNBaseline-style generation metrics: NN features use pose+shape only
  pose_only_like_baseline: false
#python main.py -c config/env.yaml scenarios/chi3d.yaml -- run.name=chi3d run.job=train

