chi3d:
  fps_train: 10
  fps_eval: 10
  augment_rotation: false
  augment_symmetry: false
  root: /home/cc/Documents/datasets/chi3d/chi3d_overfit/chi3d_smplx
  train_split_file: /home/cc/Documents/datasets/chi3d/chi3d_overfit/assets/chi3d_train.json
  test_split_file: /home/cc/Documents/datasets/chi3d/chi3d_overfit/assets/chi3d_test.json
model_denoising:
  name: transformer_unidiffuser_3
  dim_timestep_embed: 128
  params:
    dim_hidden: 312
    num_layers: 8
    dim_feedforward: 2048
    nhead: 8
model:
  data_sbj_channels: 325
  data_second_sbj_channels: 325
  denoise_mode: sample
  beta_start: 1.0e-05
  beta_end: 0.008
  beta_schedule: linear
run:
  datasets:
  - chi3d
dataloader:
  batch_size: 256
  workers: 12
  sampler: weighted
train:
  mixed_precision: 'no'
  limit_train_batches: null
  log_step_freq: 10
  checkpoint_freq: 2000
  max_steps: 300000
  limit_val_batches: null
  losses:
    denoise_1: 10.0
    denoise_2: 10.0
    smpl_v2v: 30.0
    second_smpl_v2v: 30.0
optimizer:
  type: torch
  name: AdamW
  lr: 0.00015
  weight_decay: 1.0e-06
  scale_learning_rate_with_batch_size: false
  gradient_accumulation_steps: 1
  clip_grad_norm: 5.0
  kwargs:
    betas:
    - 0.95
    - 0.999
scheduler:
  type: transformers
  name: cosine
  kwargs:
    num_warmup_steps: 5000
    num_training_steps: 50000
#python main.py -c config/env.yaml scenarios/chi3d.yaml -- run.name=chi3d2 run.job=train

